# Generated by Django 5.0 on 2023-12-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feedback_to",
            new_name="feedback_for",
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_from_company",
            field=models.BooleanField(default=False),
        ),
    ]
