# Generated by Django 5.0 on 2024-01-19 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_rename_feedback_to_feedback_feedback_for_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feedback_for",
            new_name="feedback_to",
        ),
    ]
