# Generated by Django 5.0 on 2024-02-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_rename_feedback_for_feedback_feedback_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("is_for_company", models.BooleanField(default=False)),
            ],
        ),
    ]
