# Generated by Django 5.0 on 2024-02-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="good_comment",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="improve_comment",
        ),
        migrations.AddField(
            model_name="feedback",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.question",
                    ),
                ),
            ],
        ),
    ]
