# Generated by Django 5.0 on 2024-01-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
    ]
