# Generated by Django 5.0 on 2024-01-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userdata_is_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveGroupLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=2)),
                ("folder_ids", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="userdata",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.drivegrouplink",
            ),
        ),
    ]
