# Generated by Django 5.0 on 2024-01-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_drivegrouplink_userdata_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="userdata",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.companygroup",
            ),
        ),
        migrations.CreateModel(
            name="GoogleDriveLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_link", models.CharField(max_length=200)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.companygroup",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DriveGroupLink",
        ),
    ]
