# Generated by Django 5.0 on 2024-01-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_companygroup_alter_userdata_group_googledrivelinks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googledrivelinks",
            name="folder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="googledrivelinks",
            name="drive_link",
            field=models.CharField(max_length=500),
        ),
    ]
